version: "2.1"
services:
  rabbitmqServer:
    container_name: rabbitmqServer
    image: rabbitmq:3.10.7-management
    networks:
      - rabbitnetwork
    environment:
      RABBITMQ_DEFAULT_USER: rmuser
      RABBITMQ_DEFAULT_PASS: rmpassword
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    container_name: worker
    restart: always
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - rabbitmqServer
    networks:
      - rabbitnetwork

networks:
  rabbitnetwork:
    driver: bridge
